name: Compile and push to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - frontend/src/**
      - backend/*.py
  workflow_dispatch:

jobs:
  compile-to-static:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Install dependencies
      run: npm install
      working-directory: frontend

    - name: Compile Project
      run: npm run build
      working-directory: frontend

    - name: Upload static files
      uses: actions/upload-artifact@v4.3.0
      with:
        name: static
        path: static

  build-docker:
    runs-on: ubuntu-latest
    needs: compile-to-static

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Download static files
      uses: actions/download-artifact@v4
      with:
        name: static
        path: static

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm
        push: true
        tags: ${{ vars.DOCKER_USERNAME }}/dict:latest${{ github.run_number }}

