name: Compile to deploy branch

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/compile.yml
permissions:
  contents: write

jobs:
  create-post:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Install dependencies
      run: npm install
      working-directory: frontend

    - name: Setup Git user
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Update deploy branch to main
      run: |
        git fetch
        git merge deploy main

    - name: Remove .gitignore
      run: |
        git rm .gitignore

    - name: Compile Project
      run: npm run build
      working-directory: frontend

    - name: Commit changes
      run: |
        git add -A
        git commit -m "Update static files to latest commit"
        git push origin deploy